name: Nix check

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-nix:
    runs-on: ubuntu-24.04
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6
      - uses: https://github.com/cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.EXT_GITHUB_TOKEN }}
      - name: Lint nix
        run: nix run 'nixpkgs#nixfmt-tree' -- --ci --excludes 'gen-*.nix'
      - name: Build nix
        run: nix build .
